"""
Patient Summary node — agents/patient_summary.py

Handles the `patient_summary` intent by serving the PRE-COMPUTED care summary
from SQLite (generated by the Step 1.3 batch pipeline), rather than running a
generic vector search.

This connects the offline batch layer to the online chat pipeline: the rich,
multi-source summary we already paid to compute is returned directly instead of
a lower-quality fresh retrieval.

Flow position: the graph routes here directly from the Router (bypassing
retrieval / filter / answer-gen / reviewer), then straight to Safety. The stored
summary is already Claude-generated and grounded, so it doesn't need the
generate→review loop — it goes straight to disclaimers.
"""

from __future__ import annotations

import logging

from agents.state import PipelineState
from tools.sqlite_tool import get_patient_summary

logger = logging.getLogger(__name__)

_NO_PATIENT_MSG = (
    "To summarise a patient, please select one from the sidebar first. "
    "Once a patient is selected, I can show their full care summary and answer "
    "questions tailored to their record."
)

_NO_SUMMARY_MSG = (
    "This patient does not have a pre-computed care summary yet. "
    "You can still ask specific questions about their medications or conditions."
)


def patient_summary_node(state: PipelineState) -> dict:
    """LangGraph node: serve the pre-computed patient summary from SQLite."""
    ctx = state.get("patient_context")
    trace = state.get("trace", [])

    # No patient selected → graceful message
    if not ctx or not ctx.get("patient_id"):
        trace = trace + ["PatientSummary: no patient context -> prompt to select"]
        return {
            "answer": _NO_PATIENT_MSG,
            "citations": [],
            "filtered_evidence": [],
            "review_passed": True,   # nothing to review; go straight to safety
            "trace": trace,
        }

    # Fetch the stored summary
    evidence = get_patient_summary(ctx["patient_id"])

    if not evidence:
        trace = trace + ["PatientSummary: no stored summary for patient"]
        return {
            "answer": _NO_SUMMARY_MSG,
            "citations": [],
            "filtered_evidence": [],
            "review_passed": True,
            "trace": trace,
        }

    summary = evidence[0]
    name = summary.metadata.get("name", "this patient")
    trace = trace + [f"PatientSummary: served stored summary for {name}"]

    return {
        "answer": summary.text,
        "citations": [f"[1] {summary.citation}"],
        "filtered_evidence": evidence,   # so the UI can show provenance
        "review_passed": True,           # pre-vetted content — skip the review loop
        "trace": trace,
    }


# ---------------------------------------------------------------------------
# CLI smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    from ingestion.sqlite_loader import MedDocDB
    from agents.state import new_state

    db = MedDocDB("data/meddocai.db")
    patient = db.get_patient(db.list_patients()[0]["patient_id"])

    print("=== With patient context ===")
    state = new_state("summarize this patient", patient_context=patient,
                      user_role="care_manager")
    out = patient_summary_node(state)
    print(out["answer"][:400], "...\n")
    print("citations:", out["citations"])

    print("\n=== Without patient context ===")
    state2 = new_state("summarize this patient", None, "anonymous")
    out2 = patient_summary_node(state2)
    print(out2["answer"])
