"""
FastAPI service layer — api/main.py

Exposes the agent pipeline over HTTP so it is consumable by anything, not just
the Streamlit UI. The UI becomes one client among several rather than the only
way in.

DESIGN: this is an ADAPTER, not a second implementation.
Every endpoint delegates to the same functions the UI uses —
`graph.pipeline.answer_query` and `ingestion.sqlite_loader.MedDocDB`. That is
deliberate: the Streamlit app previously grew a private copy of the pipeline
invocation which silently bypassed all observability, and collapsing it was part
of the instrumentation work. A service layer that re-implemented the pipeline
would recreate exactly that bug, one layer up.

Run:
    uvicorn api.main:app --reload --port 8000
    open http://localhost:8000/docs        # interactive OpenAPI docs
"""

from __future__ import annotations

import logging
import os
import time

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

load_dotenv(dotenv_path=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), ".env"),
            override=True)

from api.schemas import (  # noqa: E402
    EvidenceItem,
    FeedbackRequest,
    FeedbackResponse,
    HealthResponse,
    PatientDetail,
    PatientSummary,
    QueryMetrics,
    QueryRequest,
    QueryResponse,
)

logger = logging.getLogger(__name__)

DB_PATH = "data/meddocai.db"

app = FastAPI(
    title="MedDocAI API",
    version="1.0.0",
    description=(
        "Source-grounded answers about medications, health conditions, and Medicaid "
        "policy, produced by a 6-agent LangGraph pipeline with corrective-RAG "
        "self-correction.\n\n"
        "**Synthetic data only** — patient records are generated by Synthea. "
        "Answers are for demonstration and are not medical advice."
    ),
)

# The UI may be served from a different origin than the API.
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("MEDDOCAI_CORS_ORIGINS", "*").split(","),
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


def _db():
    from ingestion.sqlite_loader import MedDocDB
    return MedDocDB(DB_PATH)


@app.middleware("http")
async def add_timing_header(request: Request, call_next):
    """Server-side latency on every response — cheap, and useful to any client."""
    t0 = time.perf_counter()
    response = await call_next(request)
    response.headers["X-Process-Time-Ms"] = str(int((time.perf_counter() - t0) * 1000))
    return response


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    """Never leak a stack trace (it can contain file paths and prompt fragments)."""
    logger.exception("Unhandled error on %s", request.url.path)
    return JSONResponse(status_code=500, content={"detail": "Internal server error"})


# ---------------------------------------------------------------------------
# Health
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["ops"])
def health() -> HealthResponse:
    """Dependency-aware readiness check.

    Reports 'degraded' rather than failing, so an orchestrator can distinguish
    'the process is up but Qdrant is unreachable' from 'the process is dead'.
    """
    checks: dict = {}

    checks["anthropic_key"] = bool(os.getenv("ANTHROPIC_API_KEY"))
    checks["openai_key"] = bool(os.getenv("OPENAI_API_KEY"))

    try:
        checks["database"] = _db().count_patients() >= 0
    except Exception as e:
        checks["database"] = f"error: {str(e)[:80]}"

    # Vector store. In SERVER mode we really connect. In LOCAL (embedded) mode we
    # only stat the directory: opening an embedded store loads ~49k points (slow)
    # and, worse, CREATES the directory if absent — so a health probe on a runner
    # would leave a stray data/qdrant_storage behind. Same side-effect trap as the
    # eval harness creating an empty SQLite file in CI.
    try:
        from vector_store.client import QDRANT_PATH, is_server_mode
        if is_server_mode():
            from vector_store.client import get_qdrant_client
            names = [c.name for c in get_qdrant_client().get_collections().collections]
            checks["vector_store"] = {"mode": "server", "collections": names}
        else:
            exists = os.path.isdir(QDRANT_PATH)
            checks["vector_store"] = ({"mode": "embedded", "path": QDRANT_PATH}
                                      if exists else f"error: no store at {QDRANT_PATH}")
    except Exception as e:
        checks["vector_store"] = f"error: {str(e)[:80]}"

    ok = (checks["anthropic_key"] and checks["openai_key"]
          and checks["database"] is True
          and isinstance(checks["vector_store"], dict))
    return HealthResponse(status="ok" if ok else "degraded", checks=checks)


# ---------------------------------------------------------------------------
# Patients
# ---------------------------------------------------------------------------

@app.get("/patients", response_model=list[PatientSummary], tags=["patients"])
def list_patients(limit: int = 100) -> list[PatientSummary]:
    """The demo patient roster — the API equivalent of the sidebar selector."""
    try:
        rows = _db().list_patients(limit=limit)
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Database unavailable: {str(e)[:120]}")

    # NOTE: list_patients() selects only the roster columns — no clinical JSON — so
    # counts are NOT available here and must not be faked as zero. Clients that need
    # them call GET /patients/{id}.
    return [
        PatientSummary(
            patient_id=r["patient_id"],
            name=r.get("name", ""),
            age=r.get("age"),
            gender=r.get("gender"),
            has_summary=bool(r.get("has_summary")),
        )
        for r in rows
    ]


@app.get("/patients/{patient_id}", response_model=PatientDetail, tags=["patients"])
def get_patient(patient_id: str) -> PatientDetail:
    try:
        row = _db().get_patient(patient_id)
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Database unavailable: {str(e)[:120]}")
    if not row:
        raise HTTPException(status_code=404, detail=f"No patient with id {patient_id}")

    meds = row.get("medications_json") or []
    labs = row.get("labs_json") or []
    active = [m for m in meds if m.get("status") == "active"]
    abnormal = [l for l in labs if l.get("is_abnormal")]
    return PatientDetail(
        patient_id=row["patient_id"],
        name=row.get("name", ""),
        age=row.get("age"),
        gender=row.get("gender"),
        n_conditions=len(row.get("conditions_json") or []),
        n_active_medications=len(active),
        n_abnormal_labs=len(abnormal),
        conditions=row.get("conditions_json") or [],
        medications=active,
        abnormal_labs=abnormal,
        summary_md=row.get("summary_md"),
    )


# ---------------------------------------------------------------------------
# Query — the main endpoint
# ---------------------------------------------------------------------------

@app.post("/query", response_model=QueryResponse, tags=["query"],
          responses={404: {"description": "patient_id not found"}})
def query(req: QueryRequest) -> QueryResponse:
    """Answer one question through the full agent pipeline.

    Returns the answer twice on purpose: `answer` is the generated text, while
    `final_answer` adds the sources block and safety disclaimers. A client
    rendering to end users should show `final_answer`; a client scoring quality
    wants `answer`, since the deterministic disclaimers are not grounded in the
    retrieved evidence and would distort a faithfulness measurement.
    """
    patient_context = None
    if req.patient_id:
        try:
            patient_context = _db().get_patient(req.patient_id)
        except Exception as e:
            raise HTTPException(status_code=503, detail=f"Database unavailable: {str(e)[:120]}")
        if not patient_context:
            raise HTTPException(status_code=404, detail=f"No patient with id {req.patient_id}")

    from graph.pipeline import answer_query
    try:
        final = answer_query(
            req.question,
            patient_context=patient_context,
            user_role=req.user_role,
            max_iterations=req.max_iterations,
            conversation_history=[t.model_dump() for t in req.conversation_history],
        )
    except Exception as e:
        logger.exception("Pipeline failed")
        raise HTTPException(status_code=502, detail=f"Pipeline error: {str(e)[:200]}")

    evidence = [
        EvidenceItem(source=e.source, title=e.title, text=e.text,
                     score=e.score, citation=e.citation)
        for e in final.get("filtered_evidence", [])
    ]
    m = final.get("metrics") or {}
    return QueryResponse(
        query_id=final.get("query_id", ""),
        answer=final.get("answer", ""),
        final_answer=final.get("final_answer", final.get("answer", "")),
        citations=final.get("citations", []),
        evidence=evidence,
        disclaimers=final.get("disclaimers", []),
        intent=final.get("intent", ""),
        iterations=final.get("iteration", 0),
        review_passed=bool(final.get("review_passed", False)),
        sub_queries=final.get("sub_queries", []) or [],
        trace=final.get("trace", []),
        metrics=QueryMetrics(
            llm_calls=m.get("llm_calls", 0),
            total_tokens=m.get("total_tokens", 0),
            cost_usd=m.get("cost_usd"),
            total_latency_ms=m.get("total_latency_ms", 0.0),
        ),
    )


# ---------------------------------------------------------------------------
# Feedback
# ---------------------------------------------------------------------------

@app.post("/feedback", response_model=FeedbackResponse, tags=["feedback"],
          status_code=status.HTTP_201_CREATED)
def submit_feedback(req: FeedbackRequest) -> FeedbackResponse:
    """Record a thumbs verdict on a previous answer.

    Keyed by query_id, so re-rating replaces rather than double-counting, and the
    row joins back to that query's cost/latency metrics. Thumbs-down rows are
    harvested into candidate eval questions by scripts/feedback_to_eval.py.
    """
    db = _db()
    # Backfill the denormalised fields from this query's metrics row. An HTTP
    # client only sends a query_id, but a feedback row with no question text is
    # useless downstream — the exporter cannot build an eval candidate from it.
    # This is exactly the join query_id exists for.
    ctx = {}
    try:
        row = db.get_query_metrics(req.query_id) or {}
        ctx = {
            "question": row.get("query", ""),
            "intent": row.get("intent", ""),
            "user_role": row.get("user_role", ""),
            "patient_id": row.get("patient_id"),
            "session_id": row.get("session_id"),
            "review_passed": bool(row.get("review_passed")),
            "n_evidence": row.get("n_evidence") or 0,
        }
    except Exception:
        pass                         # a missing metrics row must not block the rating

    try:
        db.save_feedback(
            query_id=req.query_id,
            rating=req.rating,
            comment=req.comment,
            **ctx,
        )
    except ValueError as e:
        raise HTTPException(status_code=422, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Could not record feedback: {str(e)[:120]}")
    return FeedbackResponse(recorded=True, query_id=req.query_id, rating=req.rating)


@app.get("/feedback/stats", tags=["feedback"])
def feedback_stats() -> dict:
    """Aggregate thumbs counts — the improvement loop at a glance."""
    try:
        counts = _db().feedback_counts()
    except Exception as e:
        raise HTTPException(status_code=503, detail=f"Database unavailable: {str(e)[:120]}")
    total = counts["up"] + counts["down"]
    return {
        **counts,
        "total": total,
        "positive_rate": round(counts["up"] / total, 3) if total else None,
    }
